### ISSUE TITLE
Create organization faker-elixir and move project to faker-elixir/faker

### ISSUE THREAD

**Issue by vbrazo** [elixirs/faker#279]
Do you guys @igas @anthonator think this is a good idea?

In my point of view the main advantages are:
- New repos: the ability to create new repositories in the future when needed
- Communication channel: We can discuss version bump and other PRs in the organization chat

**Comment by igas** [comment]
A while ago I created https://github.com/elixirs for similar reasons, do you think we want to be restrictive to faker?

**Comment by vbrazo** [comment]
If we don't restrict to faker, which other projects would you be interested in building?

**Comment by igas** [comment]
I'm not actively developing in elixir right now, but I'm happy to bring other projects and maintainers under the org.

**Comment by igas** [comment]
Actually I do have 2 other:

- https://github.com/igas/custom_base
- https://github.com/igas/base62

+ I have one in mind to stretch my elixir a bit for https://en.wikipedia.org/wiki/Bank_state_branch :)

**Comment by vbrazo** [comment]
Bank state branch sounds like a cool challenge. Let's move to the new org.

**Comment by vbrazo** [comment]
`elixirs` works well. We just need a logo.

**Comment by igas** [comment]
@anthonator @tobyhinloopen while I'm preparing things, are you guys still keen to be maintainers?

**Comment by tobyhinloopen** [comment]
@igas I'm no longer using Elixir so I'll pass.

**Comment by anthonator** [comment]
I’m still in

**Comment by igas** [comment]
I moved repo and invited you guys. Please provide me with you hex profiles so I can add you there.

**Comment by vbrazo** [comment]
My username is `vbrazo`. Thanks!

**Comment by anthonator** [comment]
`anthonator`. Thanks!

**Comment by saulecabrera** [comment]
Recently started developing in Elixir again so if you guys need help I can give a hand as a maintainer.

**Comment by igas** [comment]
It's good to have you back @saulecabrera, lets have some fresher activity and we can come back to this discussion if others don't have any objections.
