### ISSUE TITLE
Add Dependabot?

### ISSUE THREAD

**Issue by fusillicode** [elixirs/faker#305]
I took the liberty to add [Dependabot](https://dependabot.com/) on my fork of `Faker`.

It seems however that the bot it is "transitively" tracking the original repo 🤔 

Let me know if that's ok! 😅

**Comment by anthonator** [comment]
@igas can you verify that Dependabot is on this repository?

**Comment by fusillicode** [comment]
Hi @anthonator sorry for bumping in I just want to underline that what I've written may be wrong 😓

It was the first time I added Dependabot to a repo 😅

**Comment by anthonator** [comment]
No worries!

Thanks for bringing it up. I haven't seen a Dependabot PR come up in a while so maybe it didn't transfer over.

**Comment by vbrazo** [comment]
I haven't seen it either, so we're good.
