### ISSUE TITLE
Faker.Internet.email() can generate non-valid email

### ISSUE THREAD

**Issue by Victoria91** [elixirs/faker#306]
Resulted emails can be with apostrophe which is not valid ("maximilian.o'hara@walter.org")

**Comment by anthonator** [comment]
Emails with apostrophe's are valid.

> 1 Answer. Yes, according to RFC 3696 apostrophes are valid as long as they come before the @ symbol.

https://stackoverflow.com/questions/8527180/can-there-be-an-apostrophe-in-an-email-address

**Comment by anthonator** [comment]
I'm going to go ahead and close this. Let us know if you'd like to discuss further.
