### ISSUE TITLE
Add additional publishers to Hex.pm

### ISSUE THREAD

**Issue by anthonator** [elixirs/faker#345]
I think it would be helpful to add additional publishers to Hex.pm. A lot of people’s contributions aren’t getting put to use because new versions of Faker don’t get published. @vbrazo and I are already maintainers so adding one or both of us probably makes sense.

**Comment by igas** [comment]
@anthonator I think I tried to do it already, but could not find how to add new publishers, you and @vbrazo already full access owners. I don't mind to add you both if you point me out in the right direction.

**Comment by anthonator** [comment]
Looking at `hex` mix tasks I found `mix hex.owner add PACKAGE EMAIL_OR_USERNAME`. Looks like what we need. My hex.pm username is `anthonator`.

Thanks! I think this will be a big help!

**Comment by igas** [comment]
@anthonator yep, this is what I've done from the beginning, you can check https://hex.pm/packages/faker it shows both you and @vbrazo as owners, but not publishers :(

```
$ mix hex.owner list faker
Email          Level
a***@s***.com  full
v***@g***.com  full
i***@m***.com  full
```

I'm happy to figure out how we can at least semi-automate the process. I'm happy for any one of us cut the release and if you send me an email it has higher chances of me seeing it and publish it to hex with new tag from github.

**Comment by anthonator** [comment]
We figured this out so closing. Thanks @igas!
