### ISSUE TITLE
Avatar url is redirected

### ISSUE THREAD

**Issue by Bennie-higuru** [elixirs/faker#388]
The url generated by Faker.Avatar looks like this:
```
iex> Faker.Avatar.image_url()
"http://robohash.org/set_set1/bgset_bg2/kQqaIfGqxsjFoNIT"
```
However, when I input that url in the browser it is redirected (307) to: https://robohash.org/set_set1/bgset_bg2/kQqaIfGqxsjFoNIT
Systems that do not follow a redirect path won't be able to fetch this image.

**Comment by igas** [comment]
Thank you for reporting this, #389 should fix it
