### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by frm** [elixirs/faker#512]
Hey! Would it be possible to release a v0.18 version?

v0.17 was a few years ago and ever since there have been a few PRs merged that would be helpful to have available via hex - e.g. right now v0.17's `Faker.Currency` is incompatible with `Money.Currency` due to the `ZMK` currency code having changed to `ZMW`. It's fixed on `main`/`master` but wasn't included in the `0.17` release.

**Comment by neslinesli93** [comment]
Any updates on this?

**Comment by igas** [comment]
I released 0.18
