### ISSUE TITLE
Faker.Date.date_of_birth() is failing on 29/2

### ISSUE THREAD

**Issue by MaccaCHAN** [elixirs/faker#533]
`** (MatchError) no match of right hand side value: {:error, :invalid_date}
    (faker 0.17.0) lib/faker/date.ex:21: Faker.Date.date_of_birth/1
    iex:1: (file)`

Seems this function is failing on 29/2. Got above error when calling Faker.Date.date_of_birth(). I have been using this for long time, all tests are fine until 29/2. 29/2 is the reason. Thanks.

**Comment by boon-wego** [comment]
Same here

**Comment by willyjie23** [comment]
same here

**Comment by igas** [comment]
Please let me know if 0.18 fixed the issue

**Comment by gaffney** [comment]
@igas 0.18 fixes the issue, thank you.
